import Config

# --- Static File Cache Manifest ---
# This setting tells Phoenix where to find the cache manifest for static files.
# The manifest is generated by the `mix assets.deploy` task, which hashes your static assets.
config :razzor_dev, RazzorDevWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# After running `mix assets.deploy`, this manifest ensures clients always get
# the latest version of static assets (e.g., CSS, JS, images) with proper caching.

# --- Swoosh API Client Configuration ---
# Configures the Swoosh mailer to use Finch as the HTTP client for API requests.
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: RazzorDev.Finch

# --- Swoosh Local Storage ---
# Disables local memory storage for emails in production.
# This ensures emails are sent via external services (e.g., SMTP, Mailgun).
config :swoosh, local: false

# --- Logger Configuration ---
# Sets the log level to `:info` for production.
# This suppresses debug and verbose logs, which are not needed in production.
config :logger, level: :info

# --- Database SSL Configuration ---
# Enables SSL for the database connection in production.
# `ssl: true` means the connection will use encryption.
# `ssl_opts: [verify: :verify_none]` disables certificate verification.
# For secure production deployments, you should enable verification with a CA cert file.
config :razzor_dev, RazzorDev.Repo,
  ssl: true,
  ssl_opts: [verify: :verify_none]

# --- Runtime Configuration Note ---
# Additional runtime configuration, such as secrets and environment-specific settings,
# is handled in `config/runtime.exs`. This ensures sensitive data like credentials
# are set via environment variables rather than hard-coded.
